### ISSUE TITLE
Nuxt markdown content gives 404 while hosted on github pages 

### ISSUE THREAD

**Issue by rikp777** [karngyan/karngyan.com#13]
**Describe the bug**
I started experimenting a bit, using your framework, and I came to the idea of hosting it on GitHub pages. For this I used the [following workflow](https://nuxtjs.org/deployments/github-pages/#github-actions) as documented on the site of Nuxt. This all went well, and it was easy to set up. Once everything was set up, I came to the conclusion that the Nuxt content route mapping does not work and that it always displays a 404 not found error when loading direct Nuxt markdown content via a URL.

I don't know if this is normal behavior on the github side but I thought you might know more about it since, you have focused deeply on development and working with Nuxt content. 

**To Reproduce**
- Clone the repo and then push it to a repo with the following naming convention username.github.io and since you didn't make any changes to the repo don't forget to set the Firebase to false in the config.
- Create a new .yml file in the .github/workflow folder as [described](https://nuxtjs.org/deployments/github-pages/#github-actions)
- When created, push the changes to the github test repo 
- In your GitHub repo, go to settings -> pages and change the course branch to gh-pages
- After that, click on the link indicated in a green alert box 
- When the site has loaded correctly click on projects then click on any project doesn't matter which one
- As you can see, the content loads correctly and everything is fine 
- Now reload the page as you can see you get a 404 not found error message while you would expect the content to load again 

GitHub actions workflow file as given: 
```yml 
name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Setup node env 🔧
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies 🔧
        run: yarn

      - name: Generate 🔧
        run: yarn generate

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

``` 

**Expected behavior**
The Nuxt content should also load after a refresh of the whole page.
